spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/notes_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  application:
    name: notes

testing:
  app:
    secret: SBJHPYEQUWGRVXCNVJELQTHUDVCMMSGUYQEBWRELVEGWQEARWLAKHWUYGYHREKWQPJJYAPNHYHNGQAMG